/*
 *  JavaBacula -- Java frontend of the Bacula® - The Network Backup Solution
 *  Copyright (C) 2007 by Pal DOROGI
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 *  Contact:   Pal DOROGI
 *  mailto:    pal.dorogi@gmail.com
 * 
 *  $Id$
 */

package org.ilap.javabacula.ui.dialogs;

import org.ilap.javabacula.util.BaculaConstants;
import org.ilap.javabacula.ui.util.SwingUtils;

/**
 *
 * @author  ilap
 */
public class AboutDialog extends java.awt.Dialog {
    
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initDialog();
        SwingUtils.setToCenter(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutTabbedPane = new javax.swing.JTabbedPane();
        aboutPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detailsPanel = new org.jdesktop.swingx.JXPanel();
        productVersion = new javax.swing.JLabel();
        productVersionLabel = new javax.swing.JLabel();
        userDirectory = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        userHomeLabel = new javax.swing.JLabel();
        userHome = new javax.swing.JLabel();
        userDirectoryLabel = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        productName = new javax.swing.JLabel();
        productInfromationLabel = new javax.swing.JLabel();
        javaVersionLabel = new javax.swing.JLabel();
        javaVersion = new javax.swing.JLabel();
        javaVMLabel = new javax.swing.JLabel();
        javaVM = new javax.swing.JLabel();
        javaHomeLabel = new javax.swing.JLabel();
        javaHome = new javax.swing.JLabel();
        operatingSystemLabel = new javax.swing.JLabel();
        operatingSystem = new javax.swing.JLabel();

        setResizable(false);
        setTitle("JavaBacula - About");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        aboutTabbedPane.setOpaque(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/ilap/javabacula/ui/resources/images/splash.jpg"))); // NOI18N
        aboutPanel.add(jLabel1);

        aboutTabbedPane.addTab("About", aboutPanel);

        productVersion.setText("jLabel2");

        productVersionLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        productVersionLabel.setText("Product Version:");

        userDirectory.setText("jLabel4");

        userNameLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        userNameLabel.setText("User Name:");

        userName.setText("jLabel6");

        userHomeLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        userHomeLabel.setText("User Home:");

        userHome.setText("jLabel8");

        userDirectoryLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        userDirectoryLabel.setText("User Directory:");

        productNameLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        productNameLabel.setText("Product Name:");

        productName.setText("jLabel11");

        productInfromationLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        productInfromationLabel.setText("Product Information");

        javaVersionLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        javaVersionLabel.setText("Java Version:");

        javaVersion.setText("jLabel4");

        javaVMLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        javaVMLabel.setText("Java VM:");

        javaVM.setText("jLabel8");

        javaHomeLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        javaHomeLabel.setText("Java Home:");

        javaHome.setText("jLabel13");

        operatingSystemLabel.setFont(new java.awt.Font("Dialog", 1, 12));
        operatingSystemLabel.setText("Operating System:");

        operatingSystem.setText("jLabel8");

        javax.swing.GroupLayout detailsPanelLayout = new javax.swing.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userDirectoryLabel)
                            .addComponent(userNameLabel)
                            .addComponent(userHomeLabel)
                            .addComponent(javaHomeLabel)
                            .addComponent(javaVMLabel)
                            .addComponent(javaVersionLabel)
                            .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(detailsPanelLayout.createSequentialGroup()
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(productVersionLabel)
                                        .addComponent(productNameLabel))
                                    .addGap(19, 19, 19)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(productVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailsPanelLayout.createSequentialGroup()
                                    .addComponent(operatingSystemLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(operatingSystem, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(javaVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(javaVM, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(javaHome, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userHome, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userDirectory, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(detailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(productInfromationLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productInfromationLabel)
                .addGap(16, 16, 16)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productVersionLabel)
                    .addComponent(productVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(operatingSystemLabel)
                    .addComponent(operatingSystem))
                .addGap(27, 27, 27)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaVersionLabel)
                    .addComponent(javaVersion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaVMLabel)
                    .addComponent(javaVM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(javaHomeLabel)
                    .addComponent(javaHome))
                .addGap(30, 30, 30)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userHomeLabel)
                    .addComponent(userHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(detailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDirectoryLabel)
                    .addComponent(userDirectory))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        aboutTabbedPane.addTab("Details", detailsPanel);

        add(aboutTabbedPane, java.awt.BorderLayout.CENTER);
        aboutTabbedPane.getAccessibleContext().setAccessibleName("About");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    public void initDialog() {        
       productName.setText(BaculaConstants.JB_NAME);
       productName.setToolTipText(BaculaConstants.JB_NAME);
       productVersion.setText(BaculaConstants.JB_VERSION);
       productVersion.setToolTipText(BaculaConstants.JB_VERSION);

       operatingSystem.setText(BaculaConstants.OS);
       operatingSystem.setToolTipText(BaculaConstants.OS);
       javaHome.setText(BaculaConstants.JAVA_HOME);
       javaHome.setToolTipText(BaculaConstants.JAVA_HOME);
       javaVersion.setText(BaculaConstants.JAVA_VERSION);
       javaVersion.setToolTipText(BaculaConstants.JAVA_VERSION);
       javaVM.setText(BaculaConstants.VM);
       javaVM.setToolTipText(BaculaConstants.VM);
       
       userDirectory.setText(BaculaConstants.USER_DIR);
       userDirectory.setToolTipText(BaculaConstants.USER_DIR);
       userHome.setText(BaculaConstants.USER_HOME);
       userHome.setToolTipText(BaculaConstants.USER_HOME);
       userName.setText(BaculaConstants.USER_NAME);
       userName.setToolTipText(BaculaConstants.USER_NAME);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutPanel;
    private javax.swing.JTabbedPane aboutTabbedPane;
    private org.jdesktop.swingx.JXPanel detailsPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel javaHome;
    private javax.swing.JLabel javaHomeLabel;
    private javax.swing.JLabel javaVM;
    private javax.swing.JLabel javaVMLabel;
    private javax.swing.JLabel javaVersion;
    private javax.swing.JLabel javaVersionLabel;
    private javax.swing.JLabel operatingSystem;
    private javax.swing.JLabel operatingSystemLabel;
    private javax.swing.JLabel productInfromationLabel;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productVersion;
    private javax.swing.JLabel productVersionLabel;
    private javax.swing.JLabel userDirectory;
    private javax.swing.JLabel userDirectoryLabel;
    private javax.swing.JLabel userHome;
    private javax.swing.JLabel userHomeLabel;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
    
}
