/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_ilap_javabacula_network_BaculaConnection */

#ifndef _Included_org_ilap_javabacula_network_BaculaConnection
#define _Included_org_ilap_javabacula_network_BaculaConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniCreateChannel
 * Signature: (ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniCreateChannel
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniDestroyChannel
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniDestroyChannel
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniConnect
 * Signature: (JLjava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniConnect
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniDisConnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniDisConnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniLogin
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniLogin
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniReConnect
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniReConnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniSendCommand
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniSendCommand
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniSendSignal
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniSendSignal
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniReceiveMessage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniReceiveMessage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniReplyOfCommand
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniReplyOfCommand
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniGetReplyLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniGetReplyLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniSignalToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniSignalToString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_ilap_javabacula_network_BaculaConnection
 * Method:    jniIsBnetStopped
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_ilap_javabacula_network_BaculaConnection_jniIsBnetStopped
(JNIEnv *, jobject, jlong);



#ifdef __cplusplus
}
#endif
#endif
