/*
 *  JavaBacula -- Java frontend of the Bacula® - The Network Backup Solution
 *  Copyright (C) 2007 by Pal DOROGI
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by the
 *  Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *  See the GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 * 
 *  Contact:   Pal DOROGI
 *  mailto:    pal.dorogi@gmail.com
 * 
 *  $Id$
 */

package org.ilap.swing.components;

import com.jhlabs.image.BrushedMetalFilter;
import com.jhlabs.image.GaussianFilter;
import com.jhlabs.image.MotionBlurFilter;
import com.jhlabs.image.NoiseFilter;
import com.jhlabs.image.ShadowFilter;

import org.jdesktop.swingx.painter.ImageEffect;
import org.jdesktop.swingx.painter.CompoundPainter;
import org.jdesktop.swingx.painter.GlossPainter;
import org.jdesktop.swingx.painter.MattePainter;
import org.jdesktop.swingx.painter.PinstripePainter;
import org.jdesktop.swingx.painter.ShapePainter;
import org.jdesktop.swingx.painter.TextPainter;
import org.jdesktop.swingx.painter.gradient.BasicGradientPainter;

import java.awt.Font;
import java.awt.Color;
import javax.swing.Icon;

import java.awt.RenderingHints;
import java.awt.geom.Point2D;

/**
 *
 * @author  ilap
 */
public class CoolHeader extends org.ilap.swing.components.SimpleGradientPanel {

    private TextPainter     _text;
    private ShadowFilter    _shadow;

    /** Creates new form CoolHeader */
    public CoolHeader() {
        initComponents();

        _text   = new TextPainter();
        _shadow = new ShadowFilter();
        // Beautify the Header of mainwindow
        _text.setFont(new Font("Verdana", Font.PLAIN, 18));
        _text.setPaint(Color.WHITE);
        _text.setLocation(new Point2D.Double(0.0, 0.0));
        _text.setAntialiasing(RenderingHints.VALUE_ANTIALIAS_ON);
        _text.setEffects(new ImageEffect(_shadow));

        _shadow.setAngle(-45.0f);
        _shadow.setDistance(3.0f);
        _shadow.setRadius(3.0f);
        _shadow.setOpacity(0.75f);
        _shadow.setShadowColor(Color.WHITE.getRGB());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        headerIcon = new javax.swing.JLabel();
        headerTitle = new org.jdesktop.swingx.JXPanel();

        setEndColor(new java.awt.Color(120, 140, 160));
        setStartColor(new java.awt.Color(130, 150, 170));
        headerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/ilap/swing/resources/icons/coolheader.png")));

        headerTitle.setOpaque(false);
        javax.swing.GroupLayout headerTitleLayout = new javax.swing.GroupLayout(headerTitle);
        headerTitle.setLayout(headerTitleLayout);
        headerTitleLayout.setHorizontalGroup(
            headerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );
        headerTitleLayout.setVerticalGroup(
            headerTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(headerTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(headerIcon)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel headerIcon;
    private org.jdesktop.swingx.JXPanel headerTitle;
    // End of variables declaration//GEN-END:variables

    public void setText(String text) {        
        _text.setText(text);
        headerTitle.setBackgroundPainter(_text);                
        this.updateUI();
    }
    
    public String getText() {
        return _text.getText();
    }

    public void setIcon(Icon icon) {        
        headerIcon.setIcon(icon);
        this.updateUI();
    }
    
    public Icon getIcon() {
        return headerIcon.getIcon();
    }
}
